-- Generated by Oracle SQL Developer Data Modeler 17.4.0.355.2121
--   at:        2019-11-16 11:09:46 EST
--   site:      Oracle Database 12cR2
--   type:      Oracle Database 12cR2

CREATE DATABASE IF NOT EXISTS F196083B;

USE F196083B;

CREATE TABLE account(
    email  VARCHAR(30) NOT NULL,
    pwd    VARCHAR(30) NOT NULL
);

ALTER TABLE account ADD CONSTRAINT account_pk PRIMARY KEY ( email );

INSERT INTO account VALUES('test@nyu.edu', '1234');

CREATE TABLE department (
    did     TINYINT(2) NOT NULL,
    dname   VARCHAR(20) NOT NULL,
    dtel    VARCHAR(12) NOT NULL,
    hid     SMALLINT(3) NOT NULL
);

/* Moved to CREATE TABLE
COMMENT ON COLUMN department.did IS
    'Department ID'; */

/* Moved to CREATE TABLE
COMMENT ON COLUMN department.dname IS
    'Department name'; */

/* Moved to CREATE TABLE
COMMENT ON COLUMN department.dtel IS
    'Department contact number'; */

/* Moved to CREATE TABLE
COMMENT ON COLUMN department.hid IS
    'Hospital unique id'; */

ALTER TABLE department ADD CONSTRAINT department_pk PRIMARY KEY ( did );

CREATE TABLE disease (
    deid    INT(6) NOT NULL,
    dname   VARCHAR(30) NOT NULL
);

/* Moved to CREATE TABLE
COMMENT ON COLUMN disease.deid IS
    'Disease unique id'; */

/* Moved to CREATE TABLE
COMMENT ON COLUMN disease.dname IS
    'Disease''s name'; */

ALTER TABLE disease ADD CONSTRAINT disease_pk PRIMARY KEY ( deid );

CREATE TABLE hospital (
    hid           SMALLINT(3) NOT NULL,
    hname         VARCHAR(30) NOT NULL,
    hst_address   VARCHAR(30) NOT NULL,
    hst_city      VARCHAR(30) NOT NULL,
    hstate        VARCHAR(20) NOT NULL,
    hzip          INT(5) NOT NULL
);

/* Moved to CREATE TABLE
COMMENT ON COLUMN hospital.hid IS
    'Hospital unique id'; */

/* Moved to CREATE TABLE
COMMENT ON COLUMN hospital.hname IS
    'Name of the hospital'; */

/* Moved to CREATE TABLE
COMMENT ON COLUMN hospital.hst_address IS
    'Street where the hospital located'; */

/* Moved to CREATE TABLE
COMMENT ON COLUMN hospital.hst_city IS
    'City address of the hospital'; */

/* Moved to CREATE TABLE
COMMENT ON COLUMN hospital.hstate IS
    'State of the hospital'; */

/* Moved to CREATE TABLE
COMMENT ON COLUMN hospital.hzip IS
    'zipcode of the hospital'; */

ALTER TABLE hospital ADD CONSTRAINT hospital_pk PRIMARY KEY ( hid );

CREATE TABLE patient (
    pid       INT(9) NOT NULL,
    pfname    VARCHAR(30) NOT NULL,
    plname    VARCHAR(20) NOT NULL,
    pgender   CHAR(1) NOT NULL,
    pbd       DATE NOT NULL,
    prace     VARCHAR(20),
    pstatus   CHAR(1) NOT NULL
);

/* Moved to CREATE TABLE
COMMENT ON COLUMN patient.pid IS
    'Unique patient id'; */

/* Moved to CREATE TABLE
COMMENT ON COLUMN patient.pfname IS
    'Family name of the patient'; */

/* Moved to CREATE TABLE
COMMENT ON COLUMN patient.plname IS
    'Last name of the patient'; */

/* Moved to CREATE TABLE
COMMENT ON COLUMN patient.pgender IS
    'Gender of the patient'; */

/* Moved to CREATE TABLE
COMMENT ON COLUMN patient.pbd IS
    'Patient''s birthday'; */

/* Moved to CREATE TABLE
COMMENT ON COLUMN patient.prace IS
    'Race of the patient'; */

/* Moved to CREATE TABLE
COMMENT ON COLUMN patient.pstatus IS
    'Patient''s status'; */

ALTER TABLE patient ADD CONSTRAINT patient_pk PRIMARY KEY ( pid );

CREATE TABLE patient_treatment (
    tdate     DATE NOT NULL,
    tfreq     TINYINT(1) NOT NULL,
    tstatus   CHAR(1),
    phid      INT(5) NOT NULL,
    pid       INT(9) NOT NULL,
    tid       INT(7) NOT NULL
);

/* Moved to CREATE TABLE
COMMENT ON COLUMN patient_treatment.tdate IS
    'The date that the patient took the treatment'; */

/* Moved to CREATE TABLE
COMMENT ON COLUMN patient_treatment.tfreq IS
    'Frequency that the patient take the treatment'; */

/* Moved to CREATE TABLE
COMMENT ON COLUMN patient_treatment.tstatus IS
    'Current status of the patient under this treatment'; */

/* Moved to CREATE TABLE
COMMENT ON COLUMN patient_treatment.phid IS
    'Physician unique id'; */

/* Moved to CREATE TABLE
COMMENT ON COLUMN patient_treatment.pid IS
    'Patient unique id'; */

/* Moved to CREATE TABLE
COMMENT ON COLUMN patient_treatment.tid IS
    'Treatment unique id'; */

CREATE TABLE physician (
    phid      INT(5) NOT NULL,
    phfname   VARCHAR(30) NOT NULL,
    phtel     VARCHAR(12) NOT NULL,
    phspl     VARCHAR(30) NOT NULL,
    hid       SMALLINT(3) NOT NULL
);

/* Moved to CREATE TABLE
COMMENT ON COLUMN physician.phid IS
    'Unique id for the physician '; */

/* Moved to CREATE TABLE
COMMENT ON COLUMN physician.phfname IS
    'Physician''s family name'; */

/* Moved to CREATE TABLE
COMMENT ON COLUMN physician.phtel IS
    'Physician''s phone number'; */

/* Moved to CREATE TABLE
COMMENT ON COLUMN physician.phspl IS
    'Specialization of the physician'; */

/* Moved to CREATE TABLE
COMMENT ON COLUMN physician.hid IS
    'Hospital unique id'; */

ALTER TABLE physician ADD CONSTRAINT physician_pk PRIMARY KEY ( phid );

CREATE TABLE treatment (
    tid     INT(7) NOT NULL,
    tname   VARCHAR(50) NOT NULL,
    ttype   VARCHAR(10) NOT NULL,
    deid    INT(6) NOT NULL
);

/* Moved to CREATE TABLE
COMMENT ON COLUMN treatment.tid IS
    'Unique treatment id'; */

/* Moved to CREATE TABLE
COMMENT ON COLUMN treatment.tname IS
    'Treatment name'; */

/* Moved to CREATE TABLE
COMMENT ON COLUMN treatment.ttype IS
    'Treatment type'; */

/* Moved to CREATE TABLE
COMMENT ON COLUMN treatment.deid IS
    'Foreign key of the disease table'; */

ALTER TABLE treatment ADD CONSTRAINT treatment_pk PRIMARY KEY ( tid );

CREATE TABLE users (
    usid     SMALLINT(4) NOT NULL,
    ufname   VARCHAR(20) NOT NULL,
    ulname   VARCHAR(20) NOT NULL,
    urole    VARCHAR(20) NOT NULL,
    did      TINYINT(2) NOT NULL
);

/* Moved to CREATE TABLE
COMMENT ON COLUMN users.usid IS
    'User id '; */

/* Moved to CREATE TABLE
COMMENT ON COLUMN users.ufname IS
    'User family name'; */

/* Moved to CREATE TABLE
COMMENT ON COLUMN users.ulname IS
    'Last name of the user'; */

/* Moved to CREATE TABLE
COMMENT ON COLUMN users.urole IS
    'The role of this user'; */

/* Moved to CREATE TABLE
COMMENT ON COLUMN users.did IS
    'Department unique id'; */

ALTER TABLE users ADD CONSTRAINT users_pk PRIMARY KEY ( usid );

ALTER TABLE department
    ADD CONSTRAINT department_hospital_fk FOREIGN KEY ( hid )
        REFERENCES hospital ( hid );

ALTER TABLE patient_treatment
    ADD CONSTRAINT patient_treatment_patient_fk FOREIGN KEY ( pid )
        REFERENCES patient ( pid );

ALTER TABLE patient_treatment
    ADD CONSTRAINT patient_treatment_physician_fk FOREIGN KEY ( phid )
        REFERENCES physician ( phid );

ALTER TABLE patient_treatment
    ADD CONSTRAINT patient_treatment_treatment_fk FOREIGN KEY ( tid )
        REFERENCES treatment ( tid );

ALTER TABLE physician
    ADD CONSTRAINT physician_hospital_fk FOREIGN KEY ( hid )
        REFERENCES hospital ( hid );

ALTER TABLE treatment
    ADD CONSTRAINT treatment_disease_fk FOREIGN KEY ( deid )
        REFERENCES disease ( deid );

ALTER TABLE users
    ADD CONSTRAINT users_department_fk FOREIGN KEY ( did )
        REFERENCES department ( did );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             8
-- CREATE INDEX                             0
-- ALTER TABLE                             14
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0